### ISSUE TITLE
sqldf

### ISSUE THREAD

**Issue by ggrothendieck** [eitsupi/prqlr#127]
Note that this works:

```
library(prqlr)
library(sqldf)
"from mtcars | filter cyl == 4" |> prql_compile() |> sqldf()
```

giving
```
    mpg cyl  disp  hp drat    wt  qsec vs am gear carb
1  22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
2  24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
3  22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
4  32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
5  30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
6  33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
7  21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
8  27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
9  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
10 30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
11 21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
```

**Comment by eitsupi** [comment]
Hi, thank you for your interest in this project.

We can use prqlr in combination with various existing packages, as you have noticed or as described in the following line.
https://github.com/eitsupi/prqlr/blob/d2a9a702b0fe8dba2f7a177b24ee7883ad24d48c/vignettes/prqlr.Rmd#L57

sqldf is definitely one of them.

**Comment by ggrothendieck** [comment]
but it doesn't mention sqldf even though it is easier with less setup than any of the ones mentioned

**Comment by eitsupi** [comment]
Could you please elaborate a bit more?
Also, what are you asking me to do, do you mean you want me to mention sqldf in the documentation?

**Comment by ggrothendieck** [comment]
I thought that might be a good idea. It's of course up to you but it does seem like that is easier than what is shown given that you don't need any setup such as defining a connection, etc., other than library(sqldf).
