### ISSUE TITLE
Package ‘prqlr’ was removed from the CRAN repository. Archived on 2023-08-31 for policy violation. 

### ISSUE THREAD

**Issue by eitsupi** [eitsupi/prqlr#166]

**Comment by eitsupi** [comment]
I have received an E-mail about this.

> Err, we see this still downloads. So you haven't followed the advice given by Professor Ripley. Let me cite again:
>
> "... we ask that you use the 'cargo vendor' mechanism to avoid downloading during installation and limit the number of CPUs 'cargo build' can use during installation.  Both points are covered in https://cran.r-project.org/web/packages/using_rust.html .
>
> Please correct before 2023-08-19 to safely retain your package on CRAN... "
>
> So this has been archived again.
>
>
> When offline
>
>
> >> ** using staged installation
> >> ** libs
> >> ...
> >>          cargo build --lib --release --manifest-path=./rust/Cargo.toml --target-dir ./rust/target
> >>      Updating crates.io index
> >> warning: spurious network error (3 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
> >> warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
> >> warning: spurious network error (1 tries rema iining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
>
>
> or online
>
>
> >>   Updating crates.io index
> >>   Downloading crates ...
> >>    Downloaded anstyle v1.0.2
> >>    Downloaded colorchoice v1.0.0
> >> ...
> >>
> >> And its Cargo.lock is full of things like
> >>
> >> [[package]]
> >> name = "addr2line"
> >> version = "0.21.0"
> >> source = "registry+https://github.com/rust-lang/crates.io-index"
> >> checksum = "8a30b2e23b9e17a9f90641c7ab1549cd9b44f296d3ccbf309d2863cfe398a0cb"
> >> dependencies = [
> >>   "gimli",
> >> ]
>
>
> Please follow the CRAN policies and the Rust documentation linked from there, see the URL cited above.
> You may submit a poackage with more than 5MB according to that documentation. If the check results or a team member complains, please mention you have included rust sources.
>
> Please fix and resubmit.

Perhaps I need to try again submitting a 12MB package.

**Comment by CGMossa** [comment]
Hmm.. Is this a hint? In a `.cargo/config.toml` file you can have:
```toml

[net]
retry = 3                   # network retries
git-fetch-with-cli = true   # use the `git` executable for git operations
offline = true              # do not access the network
```

Specifically choose `offline = true` as it may not be default at the moment.

**Comment by eitsupi** [comment]
Hi @CGMossa, thanks for checking that.

I did not vendoring Rust dependencies to prqlr 0.5.1 on CRAN, as described here.

https://github.com/eitsupi/prqlr/blob/ab98a469e76d9a1d7b8c50a190b5383f048720d9/cran-comments.md?plain=1#L22-L31

So downloading from crates.io was a must, but it did not seem allowed.
