### ISSUE TITLE
prqlr fails to compile on Linux arm64

### ISSUE THREAD

**Issue by andresrcs** [eitsupi/prqlr#88]
`prqlr` complains about the Rust version that comes from the OS repositories on Debian-based distros (tried with Ubuntu 22.04 LTS and RPi OS) but even after installing the latest Rust version with `rustup` (which solves the problem for Linux amd64) compilation still fails on arm64 with this error message.

```
 --- stderr
  thread 'main' panicked at 'Cannot find libR-sys bindings file for R 4.2.2false on linux in bindings. Consider compiling with --features use-bindgen.', /tmp/RtmpjWO0lb/R.INSTALL463401756134e/prqlr/src/.cargo/registry/src/github.com-1ecc6299db9ec823/libR-sys-0.3.0/build.rs:448:13
```

**Comment by eitsupi** [comment]
Thank your for letting me know about that!

I believe this is actually an extendr issue, since this package does not use libR-sys directly.
What happens if I install another package that uses extendr, like https://github.com/extendr/helloextendr? (sorry, I can't try this right now)

**Comment by andresrcs** [comment]
> What happens if you install another package that uses extendr, like https://github.com/extendr/helloextendr? (sorry, I can't try this right now)

Sadly, I get the same error message. My hope was that compilation options for `cargo` were set by you

**Comment by eitsupi** [comment]
Those files come from rextendr.
Could you please create an issue on rextendr or libR-sys?

**Comment by andresrcs** [comment]
The problem is both `rextender` and `libR-sys` (even with --features use-bindgen) compile just fine on arm64 so I don't know on what basis I can open an issue there since I'm not familiar with the Rust language.

**Comment by eitsupi** [comment]
I created a PR to add libR-sys bindings for linux/arm64 (extendr/libR-sys#133)

**Comment by andresrcs** [comment]
The new [`libR-sys`  0.4.0 release](https://github.com/extendr/libR-sys/releases/tag/v0.4.0) which includes the aarch64 bindings is available now but when installing `prqlr` it keeps downloading version 0.3.0. I gues this comes from `rextendr`?

**Comment by eitsupi** [comment]
The version of extendr is fixed here. This needs to be updated.

https://github.com/eitsupi/prqlr/blob/0d315ec23e5545e8989532c598c02110e1451a57/src/rust/Cargo.toml#L13

**Comment by eitsupi** [comment]
It appears that extendr 0.4.0 has not yet been released to crates.io.

**Comment by eitsupi** [comment]
#90 should allow installation on arm64 Linux.

**Comment by andresrcs** [comment]
I tested it on RPi OS, and it is working great! 
Do you have an estimate for a CRAN release? I would like to have this added to the [R4Pi](https://r4pi.org/) project to have a binary for RPi OS

**Comment by eitsupi** [comment]
> Do you have an estimate for a CRAN release? I would like to have this added to the [R4Pi](https://r4pi.org/) project to have a binary for RPi OS

Wow, that's fantastic!
This is a serious bug fix and I will try to submit it to CRAN in the next few days.

**Comment by eitsupi** [comment]
prqlr 0.2.1 is now on CRAN.

**Comment by andresrcs** [comment]
I see, I'll try to convince Mark (from R4Pi) to install Rust with rustup.

rustup installs per user and when I used prqlr on RStudio with my personal user rather than Pi, it worked normally. As far as I can tell, once the package is installed and up to date Rust version is no longer required right?

**Comment by eitsupi** [comment]
> I see, I'll try to convince Mark (from R4Pi) to install Rust with rustup.

Thank you for doing this. The Rust version of Debian stable is really too old... (See #49)
Ubuntu is currently 1.61, which is much newer than Debian stable, but still quite old and prql-compiler cannot be installed.

I am currently continuing to patch prql-compiler with every release of prqlr to make it buildable on older Rust versions.......

> rustup installs per user and when I used prqlr on RStudio with my personal user rather than Pi, it worked normally. As far as I can tell, once the package is installed an up to date Rust version is no longer required right?

Yes, it is required at source code build time.

**Comment by andresrcs** [comment]
FYI, a binary for aarch64 is available now in the R4Pi package repository.

It took a little while because we had to figure out some infrastructure management issues to make sure Rust can be installed consistently in the builder server without manual intervention.

**Comment by eitsupi** [comment]
@andresrcs Awesome! Thank you for working on that!

**Comment by eitsupi** [comment]
@andresrcs FYI, prqlr can be source install without Rust now.
If you don't mind using pre-built binaries, you should be able to get a fast install on the Raspberry Pi by trying something like the following, as described in the README.

```r
Sys.setenv(NOT_CRAN = "true")
install.packages("prqlr")
```

**Comment by andresrcs** [comment]
Thanks for the heads up. I do not compile `prqlr` on the Pi any more since I use the R4Pi project for binaries but I'll let them know Rust is no longer mandatory for the building tool chain
